// modules/presentation/components/Footer.tsx
import Link from 'next/link';
import { footerLinks, socialLinks } from '@/modules/presentation/data/navigation';

export default function Footer() {
  const year = new Date().getFullYear();

  return (
    <footer className="border-t border-border bg-background">
      <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="grid grid-cols-2 gap-8 md:grid-cols-3 lg:grid-cols-4">
          {/* Brand */}
          <div className="col-span-2 md:col-span-1 lg:col-span-2">
            <Link
              href="/"
              className="flex items-center gap-2 text-lg font-bold tracking-tight text-foreground hover:text-primary transition-colors"
            >
              <span className="flex size-8 items-center justify-center border border-primary bg-accent text-sm font-bold text-primary-foreground">
                S
              </span>
              <span>Sechel</span>
            </Link>
            <p className="mt-3 max-w-xs text-sm text-on-surface-variant">
              Serverless MCP memory server for AI coding agents. Persistent,
              searchable, and session-aware memory across all your tools.
            </p>
          </div>

          {/* Link Sections */}
          {footerLinks.map((section) => (
            <div key={section.title}>
              <h3 className="mb-3 text-xs font-semibold uppercase tracking-widest text-on-surface-variant">
                {section.title}
              </h3>
              <ul className="space-y-2">
                {section.links.map((link) => (
                  <li key={link.href}>
                    {link.external ? (
                      <a
                        href={link.href}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-sm text-foreground/70 hover:text-primary transition-colors"
                      >
                        {link.label}
                        <span className="ml-1 opacity-60">↗</span>
                      </a>
                    ) : (
                      <Link
                        href={link.href}
                        className="text-sm text-foreground/70 hover:text-primary transition-colors"
                      >
                        {link.label}
                      </Link>
                    )}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        {/* Bottom Bar */}
        <div className="mt-12 flex flex-col items-center gap-4 border-t border-border pt-8 sm:flex-row sm:justify-between">
          <p className="text-xs text-on-surface-variant">
            &copy; {year} Sechel. All rights reserved.
          </p>
          <div className="flex items-center gap-4">
            {socialLinks.map((link) => (
              <a
                key={link.href}
                href={link.href}
                target="_blank"
                rel="noopener noreferrer"
                className="text-sm text-on-surface-variant hover:text-primary transition-colors"
              >
                {link.label}
                <span className="ml-1 opacity-60">↗</span>
              </a>
            ))}
          </div>
        </div>
      </div>
    </footer>
  );
}

// src/lib/Footer.svelte
<script lang="ts">
  import { footerLinks, socialLinks } from '../data/navigation.ts';
  import { ExternalLink } from 'lucide-svelte';
</script>

<footer class="border-t border-[var(--border)] py-12">
  <div class="max-w-[1200px] mx-auto px-6">
    <div class="grid grid-cols-1 md:grid-cols-[2fr_1fr_1fr] gap-8">
      <div>
        <a href="#top" class="flex items-center gap-2 no-underline text-[var(--foreground)] font-bold text-lg">
          <span class="flex items-center justify-center w-8 h-8 border border-primary bg-[var(--accent)] text-[var(--primary-foreground)] text-xs font-bold">S</span>
          <span>Sechel</span>
        </a>
        <p class="text-xs text-[var(--muted-foreground)] mt-2 max-w-[300px]">Serverless MCP memory server for AI coding agents. Open source, self-hosted, MIT licensed.</p>
      </div>

      {#each footerLinks as section}
        <div>
          <h4 class="text-xs uppercase tracking-[0.08em] text-[var(--muted-foreground)] mb-4">{section.title}</h4>
          {#each section.links as link}
            {#if link.external}
              <a href={link.href} target="_blank" rel="noopener noreferrer" class="block text-sm text-[var(--on-surface-variant)] no-underline py-1 transition-colors hover:text-[var(--foreground)]">
                {link.label} <ExternalLink size={10} class="inline ml-0.5" />
              </a>
            {:else}
              <a href={link.href} class="block text-sm text-[var(--on-surface-variant)] no-underline py-1 transition-colors hover:text-[var(--foreground)]">{link.label}</a>
            {/if}
          {/each}
        </div>
      {/each}
    </div>

    <div class="mt-8 pt-6 border-t border-[var(--border)] flex justify-between text-xs text-[var(--muted-foreground)]">
      <span>&copy; {new Date().getFullYear()} Sechel. MIT License.</span>
      <div class="flex gap-4">
        {#each socialLinks as link}
          <a href={link.href} target="_blank" rel="noopener noreferrer" class="text-[var(--muted-foreground)] no-underline text-xs transition-colors hover:text-[var(--foreground)]">
            {link.label}
          </a>
        {/each}
      </div>
    </div>
  </div>
</footer>
