// modules/presentation/components/Navbar.tsx
import Link from 'next/link';
import { navLinks } from '@/modules/presentation/data/navigation';
import NavLink from '@/modules/presentation/components/NavLink';
import MobileMenu from '@/modules/presentation/components/MobileMenu';

export default function Navbar() {
  return (
    <header className="sticky top-0 z-40 border-b border-border bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/80">
      <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
        {/* Logo */}
        <Link
          href="/"
          className="flex items-center gap-2 text-lg font-bold tracking-tight text-foreground hover:text-primary transition-colors"
        >
          <span className="flex size-8 items-center justify-center border border-primary bg-accent text-sm font-bold text-primary-foreground">
            S
          </span>
          <span>Sechel</span>
        </Link>

        {/* Desktop Nav */}
        <nav className="hidden md:flex md:items-center md:gap-1">
          {navLinks.map((link) => (
            <NavLink key={link.href} link={link} />
          ))}
        </nav>

        {/* Mobile Menu Trigger */}
        <MobileMenu />
      </div>
    </header>
  );
}

// src/lib/Navbar.svelte
<script lang="ts">
  import { ExternalLink } from 'lucide-svelte';
  import { navLinks } from '../data/navigation.ts';
  import MobileMenu from './MobileMenu.svelte';
</script>

<header class="sticky top-0 z-40 border-b border-[var(--border)] bg-[var(--background)]/95 backdrop-blur-sm">
  <div class="max-w-[1200px] mx-auto px-6 flex items-center justify-between h-16">
    <a href="#top" class="flex items-center gap-2 no-underline text-[var(--foreground)] font-bold text-lg tracking-tight">
      <span class="flex items-center justify-center w-8 h-8 border border-primary bg-[var(--accent)] text-[var(--primary-foreground)] text-xs font-bold">S</span>
      <span>Sechel</span>
    </a>

    <nav class="hidden md:flex items-center gap-1">
      {#each navLinks as link}
        {#if link.external}
          <a href={link.href} target="_blank" rel="noopener noreferrer" class="px-3 py-2 text-sm text-[var(--on-surface-variant)] no-underline transition-colors border border-transparent hover:text-[var(--foreground)] hover:border-[var(--border)]">
            {link.label}
            <ExternalLink size={12} class="inline ml-0.5" />
          </a>
        {:else}
          <a href={link.href} class="px-3 py-2 text-sm text-[var(--on-surface-variant)] no-underline transition-colors border border-transparent hover:text-[var(--foreground)] hover:border-[var(--border)]">
            {link.label}
          </a>
        {/if}
      {/each}
    </nav>

    <MobileMenu {navLinks} />
  </div>
</header>
